.PHONY :8_pf_packet clean
8_pf_packet:cap1 cap2 cap3 cap4 cap5
cap1 cap2 cap3 cap4 cap5:
	gcc cap1.c -o cap1
	gcc cap2.c -o cap2
	gcc cap3.c -o cap3
	gcc cap4.c -o cap4
	gcc cap5.c -o cap5
clean:
	rm -rf cap1 cap2 cap3 cap4 cap5


